---
- name: Uninstall K3s from worker nodes
  hosts: workers
  become: true
  tasks:
    - name: Check if k3s-agent service exists
      stat:
        path: /etc/systemd/system/k3s-agent.service
      register: k3s_agent_service

    - name: Stop k3s-agent service if exists
      systemd:
        name: k3s-agent
        state: stopped
        enabled: false
      when: k3s_agent_service.stat.exists

    - name: Run k3s agent uninstall script
      command: /usr/local/bin/k3s-agent-uninstall.sh
      when: k3s_agent_service.stat.exists
      ignore_errors: true

    - name: Remove k3s agent binary
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /usr/local/bin/k3s
        - /usr/local/bin/k3s-agent
        - /usr/local/bin/k3s-agent-uninstall.sh
        - /etc/systemd/system/k3s-agent.service

    - name: Remove k3s directories and files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /var/lib/rancher/k3s
        - /etc/rancher/k3s
        - /var/lib/kubelet
        - /var/lib/cni
        - /etc/cni
        - /var/run/k3s
        - /var/log/k3s

    - name: Clean up network interfaces
      shell: |
        ip link show | grep 'cni' | awk -F': ' '{print $2}' | xargs -r -l ip link delete
        ip link show | grep 'flannel' | awk -F': ' '{print $2}' | xargs -r -l ip link delete
      ignore_errors: true

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Clean Docker containers (if present)
      shell: docker rm -f $(docker ps -aq) || true
      ignore_errors: true

    - name: Remove iptables rules
      shell: |
        iptables -F
        iptables -X
        iptables -t nat -F
        iptables -t nat -X
        iptables -t mangle -F
        iptables -t mangle -X
      ignore_errors: true
