all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    master:
      hosts:
        k3s-master:
          ansible_host: 192.168.1.106
          labels:
            resource-type: res
    workers:
      hosts:
        k3s-worker1:
          ansible_host: localhost 
          ansible_connection: local
  vars:
    ansible_user: e
    ansible_ssh_private_key_file: ~/.ssh/multipass_key
