all:
  children:
    master:
      hosts:
        k3s-master:
          ansible_host: 10.123.250.15
    workers:
      hosts:
        k3s-worker1:
          ansible_host: 10.123.250.120
          labels:
            resource-type: res
        k3s-worker2:
          ansible_host: 10.123.250.191
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/multipass_key
