apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
      - name: oauth2-server
        image: moomtp/oauth2-server:latest  # 替換為你的 Docker Hub 用戶名和映像名稱
        ports:
        - containerPort: 3000