apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
spec:
  selector:
    app: oauth2-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # 可以根據需要改為 NodePort 或 ClusterIP
