---
- name: Get info from master
  hosts: master
  tasks:
    - name: Get K3s token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: k3s_token

    - name: Set fact for K3s token
      set_fact:
        k3s_token: "{{ k3s_token['content'] | b64decode }}"
      run_once: true

    - name: Remove newline from token
      set_fact:
        k3s_token: "{{ k3s_token | regex_replace('\\n$', '') }}"

- name: Install K3s on workers
  hosts: workers
  vars:
    k3s_version: "v1.28.4+k3s2"  # Specify K3s version if needed
    k3s_server_args: "--docker"  # Use Docker instead of containerd if needed

  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: print token
      debug:
        var: hostvars['k3s-master']['k3s_token']

    - name: print URL
      debug:
        var: hostvars['k3s-master']['ansible_host']

    - name: Install first k3s agent
      when: "'k3s-agent.service' not in ansible_facts.services "
      block:
        - name: Download k3s install script
          ansible.builtin.get_url:
            url: https://get.k3s.io
            dest: /tmp/k3s_install.sh
            mode: "0755"

        - name: Execute k3s script to install agent
          ansible.builtin.command: sh /tmp/k3s_install.sh
          environment:
            K3S_URL: "https://{{ hostvars['k3s-master']['ansible_host'] }}:6443"
            # 使用剛剛註冊的變數 k3s_server_token
            K3S_TOKEN: "{{ hostvars['k3s-master']['k3s_token'] }}"
          register: install_k3s_agent
          changed_when: true

        - name: Check k3s agent server status
          ansible.builtin.systemd_service:
            name: k3s-agent.service
            state: started
            enabled: true
