all:
  children:
    master:
      hosts:
        k3s-master:
          ansible_host: 10.123.250.15
    workers:
      hosts:
        k3s-worker1:
          ansible_host: 10.123.250.226
        k3s-worker2:
          ansible_host: 10.123.250.169
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/multipass_key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    k3s_version: v1.28.4+k3s2
    ansible_python_interpreter: /usr/bin/python3
