- name: Install K3s Master
  hosts: master
  become: true
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Install K3s master
      shell: |
        export INSTALL_K3S_VERSION={{ k3s_version }}
        /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Get node token
      command: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

    - name: Store token
      set_fact:
        k3s_node_token: "{{ node_token.stdout }}"

- name: Install K3s Workers
  hosts: workers
  become: true
  tasks:
    - name: Download K3s installation script
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: '0755'

    - name: Install K3s agent
      shell: |
        export INSTALL_K3S_VERSION={{ k3s_version }}
        export K3S_URL=https://{{ hostvars[groups['master'][0]]['ansible_host'] }}:6443
        export K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_node_token'] }}
        /tmp/k3s-install.sh
      args:
        creates: /usr/local/bin/k3s
